### ISSUE TITLE
Importing from scratch sometimes fails

### ISSUE THREAD

**Issue by FredericHeem** [stellar/go-horizon#99]
On numerous occasion but not always, the following error occurs when running horizon-importer from a fresh db. To overcome this problem, drop the db again and restart.

```
History::Ledger Load (0.4ms)  SELECT  "history_ledgers".* FROM "history_ledgers"  ORDER BY "history_ledgers"."sequence" DESC LIMIT 1
  StellarCore::LedgerHeader Load (0.3ms)  SELECT  "ledgerheaders".* FROM "ledgerheaders" WHERE "ledgerheaders"."ledgerseq" = $1  ORDER BY "ledgerheaders"."ledgerhash" ASC LIMIT 1  [["ledgerseq", 1]]
  StellarCore::LedgerHeader Load (0.2ms)  SELECT  "ledgerheaders".* FROM "ledgerheaders" WHERE "ledgerheaders"."ledgerseq" = $1  ORDER BY "ledgerheaders"."ledgerhash" ASC LIMIT 1  [["ledgerseq", 1]]
  StellarCore::Transaction Load (0.2ms)  SELECT "txhistory".* FROM "txhistory" WHERE "txhistory"."ledgerseq" = $1  [["ledgerseq", 1]]
   (0.1ms)  BEGIN
  History::Account Exists (0.4ms)  SELECT  1 AS one FROM "history_accounts" WHERE "history_accounts"."id" = 0 LIMIT 1
  History::Account Exists (0.4ms)  SELECT  1 AS one FROM "history_accounts" WHERE "history_accounts"."address" = 'GCEZWKCA5VLDNRLN3RPRJMRZOX3Z6G5CHCGSNFHEYVXM3XOJMDS674JZ' LIMIT 1
   (0.2ms)  ROLLBACK
Actor crashed!
ActiveRecord::RecordInvalid: Validation failed: Id has already been taken, Address has already been taken
    /var/lib/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/validations.rb:79:in `raise_record_invalid'
    /var/lib/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/validations.rb:43:in `save!'
    /var/lib/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
    /var/lib/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/transactions.rb:291:in `block in save!'
    /var/lib/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/transactions.rb:347:in `block in with_transaction_returning_status'
    /var/lib/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
    /var/lib/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:188:in `within_new_transaction'
    /var/lib/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
    /var/lib/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/transactions.rb:220:in `transaction'
    /var/lib/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/transactions.rb:344:in `with_transaction_returning_status'
    /var/lib/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/transactions.rb:291:in `save!'
    /var/lib/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/persistence.rb:51:in `create!'
    /horizon/app/jobs/history/ledger_importer_job.rb:471:in `create_master_history_account!'
    /horizon/app/jobs/history/ledger_importer_job.rb:19:in `block in perform'
```

**Comment by nullstyle** [comment]
https://github.com/stellar/horizon-importer/pull/57 should fix this for the unavoidable case.

Note:  When running any of the re-import tasks, you should ensure there isn't another process trying to import data (i.e.  you don't have a running horizon process).
